package com.example.inf;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface IMapper<TExample,TEntity> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int countByExample(TExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int deleteByExample(TExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int insert(TEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int insertSelective(TEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    List<TEntity> selectByExample(TExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    TEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") TEntity record, @Param("example") TExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int updateByExample(@Param("record") TEntity record, @Param("example") TExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int updateByPrimaryKeySelective(TEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEntity
     *
     * @mbggenerated Sat Apr 09 14:28:32 CST 2016
     */
    int updateByPrimaryKey(TEntity record);

}
