package com.example.entity;

import java.util.List;

public class Task {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.TASK_NAME
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	private String taskName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column task.PARENT_TASK_ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	private String parentTaskId;
	
	private List<Task> childTasks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.ID
	 * @return  the value of task.ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.ID
	 * @param id  the value for task.ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.TASK_NAME
	 * @return  the value of task.TASK_NAME
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public String getTaskName() {
		return taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.TASK_NAME
	 * @param taskName  the value for task.TASK_NAME
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column task.PARENT_TASK_ID
	 * @return  the value of task.PARENT_TASK_ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public String getParentTaskId() {
		return parentTaskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column task.PARENT_TASK_ID
	 * @param parentTaskId  the value for task.PARENT_TASK_ID
	 * @mbggenerated  Sat Apr 09 14:28:32 CST 2016
	 */
	public void setParentTaskId(String parentTaskId) {
		this.parentTaskId = parentTaskId;
	}

	public List<Task> getChildTasks() {
		return childTasks;
	}

	public void setChildTasks(List<Task> childTasks) {
		this.childTasks = childTasks;
	}
	
}